name: build and push image

on: [push]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-docker-buildx@v1
        id: buildx
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - uses: actions/checkout@v1
      - name: build image
        run: sh build-latest.sh
